### ISSUE TITLE
Inappropriate files in the repository

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/OVAL-visualization-as-graph#13]
The root of the repository contains files that are "private", e.g.:

- `notes.txt`
- `playground-old.py`
- `playground-xml.py`
- `playground-xml1.py`
- `playground-xml2.py`
- `playground.py`
- `playground1.py`

they don't have value to random people that are interested in the project. They should be either moved out of the repository, or put into a special directory where they don't attract attention.

**Comment by Honny1** [comment]
The issue has been fixed in #15.

**Comment by matejak** [comment]
Great, I can confirm that!
