### ISSUE TITLE
Option to show only the failing tests

### ISSUE THREAD

**Issue by ggbecker** [OpenSCAP/OVAL-visualization-as-graph#22]
Does it make sense to have an option to show only the failing tests? As you can see, sometimes is hard to navigate between the tests
![Untitled](https://user-images.githubusercontent.com/18730394/63343428-2fe65380-c34e-11e9-90ec-2f75f29128bc.png)

**Comment by matejak** [comment]
The broader problem is that if you have negations in the tree, some passing tests may responsible for the definition to fail.

**Comment by ggbecker** [comment]
I see, so it would have to handle these special cases with negations as well. But it should be still doable.
