### ISSUE TITLE
Install instructions lead installed arf-to-graph binary to restrict permission for owner (root) only

### ISSUE THREAD

**Issue by ggbecker** [OpenSCAP/OVAL-visualization-as-graph#54]
Not sure exactly if I am doing something wrong but when I run `sudo pip3 install .` it restrict permissions to owner only.

```
$ls -la /usr/bin/arf-to-graph
-rwx------. 1 root root 400 Oct 14 21:55 /usr/bin/arf-to-graph*
```
Am I missing something?

**Comment by Honny1** [comment]
That's weird. Every time I try to install a package on a clean VM. The package is installed in `/usr/local/bin/arf-to-graph` and `/usr/local/lib/python3.7/site-packages/oval_graph`. 
I've looked at other python packages and there is no `sudo` in the installation tutorials. 
Uninstall the package and try using only `pip3 install .`. 
If it helps, let me know. @ggbecker

**Comment by ggbecker** [comment]
I managed to solve by using virtual environment.

But, let's say python is installed under prefix `/usr`, I would assume that some kind of permission is needed to install files in those places. Maybe when we get to the point that the software is packaged (rpm, deb, etc.), these kind of issues will be solved by the package installer.

Maybe adding some kind of documentation on how to install through python virtual environment can be useful.

**Comment by matejak** [comment]
Just adding 2cents - I install oval-graph using virtualenv in a local directory without issues - using `python setup.py install` worked, which is the standard way how to do things which works. You can also `python3 setup.py install --user` or `pip3 install --user` to the `$HOME/.local` prefix, which is also standard operating procedure. I don't think that we need to document SOPs extensively, but a rootless install would be nice to have mentioned somewhere.
