### ISSUE TITLE
 Redirecting command arf-to-json to file

### ISSUE THREAD

**Issue by Honny1** [OpenSCAP/OVAL-visualization-as-graph#62]
Problem with redirecting command arf-to-json to file when rule name is not unique.

**Comment by matejak** [comment]
Please tell us what exactly is the problem. Also, does it have connection to the Inquirer?

**Comment by Honny1** [comment]
Yes, there is a problem with the Inquirer. When part of the rule name or regex is used as the rule name. A selection of rules appears, but when the command is redirected to a file. Everything that is printed on the command line is saved to a file. Does not show any selection.
