### ISSUE TITLE
Embed OVAL details into the graph

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/OVAL-visualization-as-graph#66]
The oscap HTML report with OVAL details (default in oscap>=1.3) contains list of tests, and under each test, one can usually see detailed information, usually collected objects and a hint that either objects were found, but not expected, or that they were expected, but weren't found etc.
It would be nice if one could click on a test result, and the test details would pop up, or to show test details by another means.

**Comment by jan-cerny** [comment]
@matejak @Honny1 What about including an "advertisment" on the tool into the HTML report? Probably only on Fedora at this moment, but it would be nice.

**Comment by Honny1** [comment]
@jan-cerny I think it is good idea.

**Comment by Honny1** [comment]
@jan-cerny @matejak I have an idea. And what to create a command that put the charts into an html report. Command should have parameters arf and html report. Is it good idea?
